apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: dev-stack
  namespace: pulumi-system
spec:
  stack: rmishgoog/gcp-kubernetes-standard/dev
  branch: main
  destroyOnFinalize: false
  continueResyncOnCommitMatch: true
  commit: 09eba027538b1a3c05ddb3b7732b3f98c48c338e
  envRefs:
    GOOGLE_CREDENTIALS:
      type: Secret
      secret:
        key: GOOGLE_APPLICATION_CREDENTIALS
        name: google-cloud-access-token
        namespace: pulumi-system
    PULUMI_ACCESS_TOKEN:
      type: Secret
      secret:
        key: pulumi-token
        name: pulumi-token
        namespace: pulumi-system
  projectRepo: https://github.com/rmishgoog/pulumi-cloud-kubernetes
  gitAuth:
    accessToken:
      type: Secret
      secret:
        key: git-token
        name: git-token
        namespace: pulumi-system